# Generated by Django 5.1.2 on 2025-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alumniprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('released', 'Released'), ('blocked_due_to_balance', 'Blocked Due to Balance')], default='draft', max_length=30),
        ),
    ]
