# Generated by Django 5.1.2 on 2025-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_documentrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='preferred_release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
