# Generated by Django 5.1.2 on 2025-07-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_clearancesignatory_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('0', 'None')], default='0', max_length=1),
        ),
    ]
