# Generated by Django 5.1.2 on 2025-07-23 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_documentrequest_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('academic_year', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollment_forms',
                'ordering': ['-created_at'],
            },
        ),
    ]
