# Generated by Django 5.1.2 on 2025-07-23 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_enrollmentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grad_date', models.DateField()),
                ('grad_appno', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('thesis_title', models.CharField(blank=True, max_length=255, null=True)),
                ('subjects', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'graduation_forms',
                'ordering': ['-created_at'],
            },
        ),
    ]
