# Generated by Django 5.1.2 on 2025-07-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_graduationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationform',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
