# Generated by Django 5.1.2 on 2025-07-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_graduationform_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationform',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='graduationform',
            name='present_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
