# Generated by Django 4.2.9 on 2025-07-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_graduationform_permanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceform',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
