# Generated by Django 5.1.2 on 2025-08-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancesignatory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
