# Generated by Django 5.1.2 on 2025-08-01 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_clearancesignatory_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSignatory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='landing.enrollmentform')),
                ('signatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollment_signatories',
            },
        ),
    ]
