# Generated by Django 5.1.2 on 2025-08-03 04:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_graduationsignatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatoryProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signatory_type', models.CharField(choices=[('dorm_supervisor', 'Dorm Supervisor'), ('canteen_concessionaire', 'Canteen Concessionaire'), ('library_director', 'Library Director'), ('scholarship_director', 'Scholarship Director'), ('it_director', 'IT Director'), ('student_affairs', 'Student Affairs'), ('cashier', 'Cashier'), ('business_manager', 'Business Manager'), ('registrar', 'Registrar'), ('academic_dean', 'Academic Dean')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signatory_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signatory_profiles',
            },
        ),
    ]
