# Generated by Django 5.1.2 on 2025-08-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_registrarprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancesignatory',
            name='seen_by_signatory',
            field=models.BooleanField(default=False),
        ),
    ]
