# Generated by Django 5.1.2 on 2025-08-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_clearancesignatory_seen_by_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatoryprofile',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signatoryprofile',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signatoryprofile',
            name='pin_set',
            field=models.BooleanField(default=False),
        ),
    ]
