# Generated by Django 5.1.2 on 2025-08-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_signatoryprofile_force_password_change_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clearancesignatory',
            index=models.Index(fields=['clearance', 'signatory'], name='clearance_s_clearan_c3123d_idx'),
        ),
        migrations.AddIndex(
            model_name='clearancesignatory',
            index=models.Index(fields=['status'], name='clearance_s_status_2c9028_idx'),
        ),
        migrations.AddIndex(
            model_name='clearancesignatory',
            index=models.Index(fields=['signatory', 'status'], name='clearance_s_signato_670d47_idx'),
        ),
        migrations.AddIndex(
            model_name='clearancesignatory',
            index=models.Index(fields=['seen_by_signatory'], name='clearance_s_seen_by_bbc303_idx'),
        ),
    ]
