# Generated by Django 5.1.2 on 2025-08-06 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_clearancesignatory_clearance_s_clearan_c3123d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('approved_forms', 'Approved Forms'), ('pending_forms', 'Pending Forms'), ('disapproved_forms', 'Disapproved Forms')], max_length=20)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'auto_generated_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatoryActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('disapprove', 'Disapprove'), ('view', 'View'), ('print', 'Print'), ('delete', 'Delete')], max_length=20)),
                ('form_type', models.CharField(choices=[('clearance', 'Clearance'), ('enrollment', 'Enrollment'), ('graduation', 'Graduation')], max_length=20)),
                ('form_id', models.UUIDField()),
                ('student_name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('location_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signatory_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
