# Generated by Django 5.1.2 on 2025-08-08 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_autogeneratedreport_signatoryactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='autogeneratedreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_generated_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
