# Generated by Django 5.1.2 on 2025-08-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_autogeneratedreport_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarprofile',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrarprofile',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='registrarprofile',
            name='pin_set',
            field=models.BooleanField(default=False),
        ),
    ]
