# Generated by Django 5.1.2 on 2025-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_registrarprofile_force_password_change_and_more'),
    ]

    operations = [
        # Add indexes for AuditLog optimization
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON audit_logs (timestamp DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_audit_log_timestamp;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_audit_log_user_action ON audit_logs (user_id, action_type);",
            reverse_sql="DROP INDEX IF EXISTS idx_audit_log_user_action;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_audit_log_action_type ON audit_logs (action_type);",
            reverse_sql="DROP INDEX IF EXISTS idx_audit_log_action_type;"
        ),
        
        # Add indexes for SignatoryActivityLog optimization
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_signatory_log_timestamp ON signatory_activity_logs (created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_signatory_log_timestamp;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_signatory_log_action ON signatory_activity_logs (action_type);",
            reverse_sql="DROP INDEX IF EXISTS idx_signatory_log_action;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_signatory_log_signatory ON signatory_activity_logs (signatory_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_signatory_log_signatory;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_signatory_log_form_type ON signatory_activity_logs (form_type);",
            reverse_sql="DROP INDEX IF EXISTS idx_signatory_log_form_type;"
        ),
        
        # Add composite indexes for common query patterns
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp_action ON audit_logs (timestamp DESC, action_type);",
            reverse_sql="DROP INDEX IF EXISTS idx_audit_log_timestamp_action;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_signatory_log_timestamp_action ON signatory_activity_logs (created_at DESC, action_type);",
            reverse_sql="DROP INDEX IF EXISTS idx_signatory_log_timestamp_action;"
        ),
    ]
