# Generated by Django 5.1.2 on 2025-08-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_auto_20250810_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='report_period',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='target_user',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='period_end',
            field=models.DateField(blank=True, help_text='End of reporting period', null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='period_start',
            field=models.DateField(blank=True, help_text='Start of reporting period', null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='report_type',
            field=models.CharField(choices=[('clearance', 'Clearance'), ('enrollment', 'Enrollment'), ('graduation', 'Graduation'), ('document_release', 'Document Release'), ('clearance_pack', 'Clearance Pack'), ('enrollment_pack', 'Enrollment Pack'), ('graduation_pack', 'Graduation Pack'), ('manual_activity', 'Manual Activity Report')], max_length=50),
        ),
    ]
