# Generated by Django 5.1.2 on 2025-08-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_update_generated_report_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum of the file', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='period_end',
            field=models.DateField(blank=True, db_index=True, help_text='End of reporting period', null=True),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='period_start',
            field=models.DateField(blank=True, db_index=True, help_text='Start of reporting period', null=True),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='report_type',
            field=models.CharField(choices=[('clearance', 'Clearance'), ('enrollment', 'Enrollment'), ('graduation', 'Graduation'), ('document_release', 'Document Release'), ('clearance_pack', 'Clearance Pack'), ('enrollment_pack', 'Enrollment Pack'), ('graduation_pack', 'Graduation Pack'), ('manual_activity', 'Manual Activity Report')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['report_type', 'created_at'], name='gr_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['report_type', 'period_start', 'period_end'], name='gr_type_period_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['generated_by', 'created_at'], name='gr_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status', 'created_at'], name='gr_status_created_idx'),
        ),
    ]
