# Generated by Django 5.1.2 on 2025-08-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_add_generatedreport_indexes_and_checksum'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='generatedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('period_end__isnull', False), ('period_start__isnull', False)), fields=('report_type', 'period_start', 'period_end'), name='unique_report_per_period'),
        ),
    ]
