# Generated by Django 5.1.2 on 2025-08-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_add_unique_constraint_per_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='business_manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='business_manager_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='business_manager_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
