# Generated by Django 5.1.2 on 2025-08-14 07:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0030_documentrequest_business_manager_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessManagerActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('disapprove', 'Disapprove'), ('view', 'View'), ('print', 'Print'), ('delete', 'Delete')], max_length=20)),
                ('form_type', models.CharField(choices=[('clearance', 'Clearance'), ('enrollment', 'Enrollment'), ('graduation', 'Graduation'), ('credential', 'Credential Request')], max_length=20)),
                ('form_id', models.UUIDField()),
                ('student_name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('location_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bm_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_manager_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
