# Generated by Django 5.1.2 on 2025-08-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0033_alter_message_options_remove_message_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
