# Generated by Django 5.1.2 on 2025-08-19 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_studentprofile_emergency_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_on_form_approved', models.BooleanField(default=True)),
                ('email_on_form_disapproved', models.BooleanField(default=True)),
                ('email_on_document_ready', models.BooleanField(default=True)),
                ('email_on_clearance_completed', models.BooleanField(default=True)),
                ('email_daily_digest', models.BooleanField(default=True)),
                ('notify_form_submissions', models.BooleanField(default=True)),
                ('notify_status_changes', models.BooleanField(default=True)),
                ('notify_document_updates', models.BooleanField(default=True)),
                ('notify_system_alerts', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='daily', max_length=10)),
                ('digest_time', models.TimeField(default='18:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('form_submitted', 'Form Submitted'), ('form_approved', 'Form Approved'), ('form_disapproved', 'Form Disapproved'), ('document_ready', 'Document Ready'), ('document_released', 'Document Released'), ('clearance_completed', 'Clearance Completed'), ('daily_digest', 'Daily Digest'), ('report_generated', 'Report Generated')], max_length=30, unique=True)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_template', models.TextField(help_text='Email template with placeholders')),
                ('in_app_title', models.CharField(max_length=255)),
                ('in_app_message', models.TextField(help_text='In-app notification template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='action_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Additional notification data', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='form_id',
            field=models.UUIDField(blank=True, help_text='ID of the related form', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='form_type',
            field=models.CharField(blank=True, choices=[('clearance', 'Clearance'), ('enrollment', 'Enrollment'), ('graduation', 'Graduation'), ('document_request', 'Document Request')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('form_approved', 'Form Approved'), ('form_disapproved', 'Form Disapproved'), ('document_ready', 'Document Ready for Release'), ('document_released', 'Document Released'), ('report_generated', 'Report Generated'), ('clearance_completed', 'Clearance Completed'), ('system_alert', 'System Alert'), ('deadline_reminder', 'Deadline Reminder')], default='system_alert', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='settlement_period',
            field=models.DurationField(blank=True, help_text='Time given to resolve issues', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_63f199_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_4b40ec_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['email_sent', 'created_at'], name='notificatio_email_s_445e2f_idx'),
        ),
        migrations.AddField(
            model_name='emailnotificationlog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.notification'),
        ),
        migrations.AddField(
            model_name='emailnotificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailnotificationlog',
            index=models.Index(fields=['user', 'email_type'], name='email_notif_user_id_0d6a02_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotificationlog',
            index=models.Index(fields=['status', 'created_at'], name='email_notif_status_c7e786_idx'),
        ),
    ]
