# Generated by Django 5.1.2 on 2025-08-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_emailnotificationlog_notificationpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Scheduler',
                'verbose_name_plural': 'Report Schedulers',
                'db_table': 'report_scheduler',
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='clearanceform',
            options={'ordering': ['-submitted_at']},
        ),
    ]
