# Generated by Django 5.1.2 on 2025-08-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0036_reportscheduler_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='report_type',
            field=models.CharField(choices=[('clearance', 'Clearance'), ('enrollment', 'Enrollment'), ('graduation', 'Graduation'), ('document_release', 'Document Release'), ('clearance_pack', 'Clearance Pack'), ('enrollment_pack', 'Enrollment Pack'), ('graduation_pack', 'Graduation Pack'), ('manual_activity', 'Activity Report')], db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='clearancesignatory',
            constraint=models.UniqueConstraint(fields=('clearance', 'signatory'), name='unique_clearance_signatory'),
        ),
    ]
