# Generated by Django 5.1.2 on 2025-08-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0037_alter_generatedreport_report_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=4)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('signatory', 'Signatory'), ('admin', 'Admin'), ('business_manager', 'Business Manager')], max_length=20)),
                ('signup_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'otp_verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='signatoryprofile',
            name='signatory_type',
            field=models.CharField(choices=[('dorm_supervisor', 'Dorm Supervisor'), ('canteen_concessionaire', 'Canteen Concessionaire'), ('library_director', 'Library Director'), ('scholarship_director', 'Scholarship Director'), ('it_director', 'IT Director'), ('student_affairs', 'Student Affairs'), ('cashier', 'Cashier'), ('business_manager', 'Business Manager'), ('registrar', 'Registrar'), ('academic_dean', 'Academic Dean'), ('president', 'President')], max_length=50),
        ),
    ]
