# Generated by Django 5.1.2 on 2025-08-31 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0039_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=20)),
                ('duration_years', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academic_programs',
                'ordering': ['program_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester_number', models.IntegerField()),
                ('semester_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'academic_semesters',
                'ordering': ['year_level', 'semester_number'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('professor', models.CharField(default='TBA', max_length=100)),
                ('units', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='landing.academicsemester')),
            ],
            options={
                'db_table': 'academic_subjects',
                'ordering': ['semester', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYearLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_number', models.IntegerField()),
                ('year_name', models.CharField(max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_levels', to='landing.academicprogram')),
            ],
            options={
                'db_table': 'academic_year_levels',
                'ordering': ['program', 'year_number'],
                'unique_together': {('program', 'year_number')},
            },
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='landing.academicyearlevel'),
        ),
        migrations.AlterUniqueTogether(
            name='academicsemester',
            unique_together={('year_level', 'semester_number')},
        ),
    ]
