# Generated by Django 5.1.2 on 2025-08-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0040_academicprogram_academicsemester_academicsubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='subjects',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
