# Generated by Django 5.1.2 on 2025-08-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0041_enrollmentform_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentform',
            name='semester',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentform',
            name='section',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
