# Generated by Django 5.1.2 on 2025-09-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0042_enrollmentform_semester_alter_enrollmentform_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationform',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graduationform',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graduationform',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
