# Generated by Django 5.1.2 on 2025-09-13 04:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0043_graduationform_first_name_graduationform_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('signup_data', models.JSONField()),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pending_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_users',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
