# Generated by Django 5.1.2 on 2025-09-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0044_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_on_enrollment_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_on_graduation_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('form_approved', 'Form Approved'), ('form_disapproved', 'Form Disapproved'), ('document_ready', 'Document Ready'), ('document_released', 'Document Released'), ('clearance_completed', 'Clearance Completed'), ('enrollment_completed', 'Enrollment Completed'), ('graduation_completed', 'Graduation Completed'), ('daily_digest', 'Daily Digest'), ('report_generated', 'Report Generated')], max_length=30, unique=True),
        ),
    ]
