from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('google-oauth/', views.google_oauth_login, name='google_oauth_login'),
    path('google-callback/', views.google_oauth_callback, name='google_oauth_callback'),
    path('check-profile-completion/', views.check_profile_completion, name='check_profile_completion'),
    path('complete-profile/', views.complete_profile, name='complete_profile'),
    
    # Messaging endpoints
    path('api/conversations/', views.get_conversations, name='get_conversations'),
    path('api/conversations/<uuid:conversation_id>/messages/', views.get_conversation_messages, name='get_conversation_messages'),
    path('api/send-message/', views.send_message, name='send_message'),
    path('api/users-for-conversation/', views.get_users_for_new_conversation, name='get_users_for_conversation'),
    path('api/start-conversation/', views.start_conversation, name='start_conversation'),
    
    # Notification API endpoints
    path('api/notifications/', views.get_notifications_api, name='get_notifications_api'),
    path('api/notifications/enhanced/', views.get_notifications_enhanced_api, name='get_notifications_enhanced_api'),
    path('api/notifications/stats/', views.get_notification_stats_api, name='get_notification_stats_api'),
    path('api/notifications/preferences/', views.notification_preferences_api, name='notification_preferences_api'),
    path('api/notifications/<uuid:notification_id>/read/', views.mark_notification_read_api, name='mark_notification_read_api'),
    path('api/notifications/mark-all-read/', views.mark_all_notifications_read_api, name='mark_all_notifications_read_api'),
    path('api/browser-notifications/', views.api_browser_notifications, name='api_browser_notifications'),
    path('api/mark-browser-notification-shown/', views.api_mark_browser_notification_shown, name='api_mark_browser_notification_shown'),
    path("", views.landing),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('verify-otp-submit/', views.verify_otp_submit, name='verify_otp_submit'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),
    path('waiting-approval/', views.waiting_approval, name='waiting_approval'),
    
    # Pending User Management APIs
    path('api/pending-users/', views.api_pending_users, name='api_pending_users'),
    path('api/pending-users/<uuid:user_id>/', views.api_pending_user_details, name='api_pending_user_details'),
    path('api/pending-users/<uuid:user_id>/approve/', views.api_approve_pending_user, name='api_approve_pending_user'),
    path('api/pending-users/<uuid:user_id>/decline/', views.api_decline_pending_user, name='api_decline_pending_user'),
    path('dashboard/', views.students, name='student_dashboard'),
    path('graduation/view/current/', views.student_graduation_current, name='student_graduation_current'),
    path('enrollment/view/current/', views.student_enrollment_current, name='student_enrollment_current'),
    path('student/graduation/pdf/', views.student_graduation_pdf, name='student_graduation_pdf'),
    path('student/enrollment/pdf/', views.student_enrollment_pdf, name='student_enrollment_pdf'),
    path('log-in/', views.login, name="login"),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('forgot-password-submit/', views.forgot_password_submit, name='forgot_password_submit'),
    path('reset-password/<str:token>/', views.reset_password, name='reset_password'),
    path('reset-password-submit/', views.reset_password_submit, name='reset_password_submit'),
    path("trial/", views.trial),
    path('signup/student/', views.student_signup, name='student_signup'),
    path('signup/alumni/', views.alumni_signup, name='alumni_signup'),
    path('log-in-view/', views.login_view, name='login-view'),
    path('logout/', views.logout_view, name='logout'),
    path('submit-request/', views.handle_request, name='submit_request'),
    path('delete-request/<uuid:request_id>/', views.delete_request, name='delete_request'),
    path('view-request/<uuid:request_id>/', views.view_request, name='view_request'),
    path('profile/', views.handle_profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('check-request-history/', views.check_request_history, name='check_request_history'),
    path('get-request-data/<uuid:request_id>/', views.get_request_data, name='get_request_data'),
    path('submit-clearance/', views.submit_clearance_form, name='submit_clearance'),
    path('check-clearance-history/', views.check_clearance_history, name='check_clearance_history'),
    path('view-clearance/<uuid:id>/', views.view_clearance, name='view_clearance'),
    path('get-clearance-data/<uuid:clearance_id>/', views.get_clearance_data, name='get_clearance_data'),
    path('enrollment/history/', views.enrollment_history, name='enrollment_history'),
    path('enrollment/submit/', views.submit_enrollment_form, name='submit_enrollment_form'),
    path('enrollment/delete/<int:form_id>/', views.delete_enrollment, name='delete_enrollment'),
    path('enrollment/view/<uuid:form_id>/', views.view_enrollment, name='view_enrollment'),
    path('graduation/submit/', views.submit_graduation_form, name='submit_graduation_form'),
    path('graduation/view/<uuid:form_id>/', views.view_graduation, name='view_graduation'),

    # ========================================
    # REGISTRAR URLS
    # ========================================
    path('registrar/dashboard/', views.registrar_dashboard, name='registrar_dashboard'),
    path('registrar/clearance/', views.registrar_clearance, name='registrar_clearance'),
    path('registrar/clearance/api/data/', views.clearance_data_api, name='clearance_data_api'),
    path('registrar/clearance/approve/', views.approve_clearance, name='approve_clearance'),
    path('registrar/clearance/disapprove/', views.disapprove_clearance, name='disapprove_clearance'),
    path('registrar/clearance/print/<uuid:clearance_id>/', views.print_clearance, name='print_clearance'),
    path('registrar/clearance/bulk-print/', views.bulk_print_clearance, name='bulk_print_clearance'),
    path('registrar/clearance/preview-print/', views.preview_print_clearance, name='preview_print_clearance'),
    path('registrar/clearance/delete/<uuid:clearance_id>/', views.delete_clearance, name='delete_clearance'),
    path('registrar/clearance/bulk-delete/', views.bulk_delete_clearance, name='bulk_delete_clearance'),
    path('registrar/clearance/bulk-approve/', views.bulk_approve_clearance, name='bulk_approve_clearance'),
    path('registrar/clearance/bulk-disapprove/', views.bulk_disapprove_clearance, name='bulk_disapprove_clearance'),
    path('registrar/enrollment/', views.registrar_enrollment, name='registrar_enrollment'),
    path('registrar/enrollment/api/data/', views.enrollment_data_api, name='enrollment_data_api'),
    path('registrar/enrollment/approve/', views.approve_enrollment, name='approve_enrollment'),
    path('registrar/enrollment/disapprove/', views.disapprove_enrollment, name='disapprove_enrollment'),
    path('registrar/enrollment/bulk-approve/', views.bulk_approve_enrollment, name='bulk_approve_enrollment'),
    path('registrar/enrollment/bulk-disapprove/', views.bulk_disapprove_enrollment, name='bulk_disapprove_enrollment'),
    path('registrar/enrollment/delete/<uuid:enrollment_id>/', views.delete_enrollment_registrar, name='delete_enrollment_registrar'),
    path('registrar/enrollment/bulk-delete/', views.bulk_delete_enrollment, name='bulk_delete_enrollment'),
    path('registrar/enrollment/print/<uuid:enrollment_id>/', views.print_enrollment, name='print_enrollment'),
    path('registrar/enrollment/bulk-print/', views.bulk_print_enrollment, name='bulk_print_enrollment'),
    path('registrar/enrollment/preview-print/', views.preview_print_enrollment, name='preview_print_enrollment'),
    path('registrar/graduation/', views.registrar_graduation, name='registrar_graduation'),
    path('registrar/graduation/api/data/', views.graduation_data_api, name='graduation_data_api'),
    path('registrar/graduation/approve/', views.approve_graduation, name='approve_graduation'),
    path('registrar/graduation/disapprove/', views.disapprove_graduation, name='disapprove_graduation'),
    path('registrar/graduation/bulk-approve/', views.bulk_approve_graduation, name='bulk_approve_graduation'),
    path('registrar/graduation/bulk-disapprove/', views.bulk_disapprove_graduation, name='bulk_disapprove_graduation'),
    path('registrar/graduation/delete/<uuid:graduation_id>/', views.delete_graduation_registrar, name='delete_graduation_registrar'),
    path('registrar/graduation/bulk-delete/', views.bulk_delete_graduation, name='bulk_delete_graduation'),
    path('registrar/graduation/view/<uuid:graduation_id>/', views.view_graduation_registrar, name='view_graduation_registrar'),
    path('registrar/graduation/print/<uuid:graduation_id>/', views.print_graduation, name='print_graduation'),
    path('registrar/graduation/bulk-print/', views.bulk_print_graduation, name='bulk_print_graduation'),
    path('registrar/graduation/preview-print/', views.preview_print_graduation, name='preview_print_graduation'),
    path('registrar/courses/', views.registrar_courses, name='registrar_courses'),
    path('api/academic-programs/', views.academic_programs_api, name='academic_programs_api'),
    path('api/courses/', views.courses_api, name='courses_api'),
    path('api/courses/<uuid:course_id>/', views.course_detail_api, name='course_detail_api'),
    path('api/courses/create/', views.create_course_api, name='create_course_api'),
    path('api/courses/<uuid:course_id>/update/', views.update_course_api, name='update_course_api'),
    path('api/courses/signup/', views.courses_for_signup_api, name='courses_for_signup_api'),
    path('api/enrollment/programs/', views.enrollment_programs_api, name='enrollment_programs_api'),
    path('api/enrollment/year-levels/', views.enrollment_year_levels_api, name='enrollment_year_levels_api'),
    path('api/enrollment/subjects/', views.enrollment_subjects_api, name='enrollment_subjects_api'),
    path('registrar/document-release/', views.registrar_document_release, name='registrar_document_release'),
    path('registrar/document-release/api/data/', views.document_release_data_api, name='document_release_data_api'),
    path('registrar/document-release/submit-date/', views.submit_release_date, name='submit_release_date'),
    path('registrar/document-release/update-date/', views.update_release_date, name='update_release_date'),
    path('registrar/document-release/update-status/', views.update_document_status, name='update_document_status'),
    path('registrar/document-release/delete/<uuid:document_request_id>/', views.delete_document_release, name='delete_document_release'),
    path('registrar/document-release/bulk-delete/', views.bulk_delete_document_release, name='bulk_delete_document_release'),
    path('registrar/reports/', views.registrar_reports, name='registrar_reports'),
    path('registrar/reports/api/data/', views.registrar_reports_data_api, name='registrar_reports_data_api'),
    path('registrar/reports/export/csv/', views.registrar_reports_csv_export, name='registrar_reports_csv_export'),
    path('registrar/reports/api/list/', views.registrar_reports_list_api, name='registrar_reports_list_api'),
    path('registrar/reports/forms/api/list/', views.registrar_forms_list_api, name='registrar_forms_list_api'),
    path('registrar/forms/<str:form_type>/<uuid:form_id>/download/', views.registrar_form_download, name='registrar_form_download'),
    path('registrar/forms/<str:form_type>/<uuid:form_id>/view/', views.registrar_form_view, name='registrar_form_view'),
    path('registrar/reports/generate/', views.registrar_generate_manual_report, name='registrar_generate_manual_report'),
    path('registrar/reports/generate-pack/', views.registrar_generate_signatory_pack, name='registrar_generate_signatory_pack'),
    path('registrar/reports/download-report/<uuid:report_id>/', views.registrar_download_report, name='registrar_download_report'),
    path('registrar/reports/regenerate-weekly/', views.registrar_regenerate_weekly_report, name='registrar_regenerate_weekly_report'),
    path('registrar/user-management/', views.registrar_user_management, name='registrar_user_management'),
    path('registrar/user-management/api/data/', views.user_management_data_api, name='user_management_data_api'),
    path('registrar/user-management/api/create/', views.create_user_api, name='create_user_api'),
    path('registrar/user-management/api/delete/<uuid:user_id>/', views.delete_user_api, name='delete_user_api'),
    path('registrar/user-management/api/user/<uuid:user_id>/', views.get_user_details_api, name='get_user_details_api'),
    path('registrar/profile/', views.registrar_profile, name='registrar_profile'),
    path('registrar/profile/api/data/', views.registrar_profile_data_api, name='registrar_profile_data_api'),
    path('registrar/profile/update/', views.registrar_profile_update_api, name='registrar_profile_update_api'),
    path('registrar/profile/change-password/', views.registrar_profile_change_password_api, name='registrar_profile_change_password_api'),
    path('registrar/profile/upload-picture/', views.registrar_profile_upload_picture_api, name='registrar_profile_upload_picture_api'),
    
    # Registrar PIN setup endpoints
    path('registrar/set-pin/', views.registrar_set_pin, name='registrar_set_pin'),
    path('registrar/change-pin/', views.registrar_change_pin, name='registrar_change_pin'),
    path('registrar/verify-pin/', views.registrar_verify_pin, name='registrar_verify_pin'),
    path('registrar/check-setup-status/', views.registrar_check_setup_status, name='registrar_check_setup_status'),
    path('registrar/change-password/', views.registrar_change_password, name='registrar_change_password'),
    
    path('registrar/messages/', views.registrar_messages, name='registrar_messages'),
    
    # API endpoints
    path('registrar/dashboard/api/data/', views.dashboard_data_api, name='dashboard_data_api'),
    
    # Calendar Event Management
    path('registrar/calendar/events/', views.calendar_events_api, name='calendar_events_api'),
    path('registrar/calendar/events/add/', views.add_calendar_event, name='add_calendar_event'),
    path('registrar/calendar/events/<str:event_id>/edit/', views.edit_calendar_event, name='edit_calendar_event'),
    path('registrar/calendar/events/<str:event_id>/delete/', views.delete_calendar_event, name='delete_calendar_event'),

    # ========================================
    # SIGNATORY URLS
    # ========================================
    path('signatory/dashboard/', views.signatory_dashboard, name='signatory_dashboard'),
    path('signatory/dashboard/api/data/', views.signatory_dashboard_data_api, name='signatory_dashboard_data_api'),
    path('signatory/dashboard/mark-seen/', views.signatory_mark_clearance_seen, name='signatory_mark_clearance_seen'),
    path('signatory/clearance/', views.signatory_clearance, name='signatory_clearance'),
    path('signatory/enrollment/', views.signatory_enrollment, name='signatory_enrollment'),
    path('signatory/profile/', views.signatory_profile, name='signatory_profile'),
    path('signatory/messages/', views.signatory_messages, name='signatory_messages'),
    path('signatory/reports/', views.signatory_reports, name='signatory_reports'),
    
    # Signatory Calendar Events
    path('signatory/calendar/events/', views.signatory_calendar_events_api, name='signatory_calendar_events_api'),
    path('signatory/calendar/events/add/', views.signatory_add_calendar_event, name='signatory_add_calendar_event'),
    
    # Signatory Filter Options
    path('signatory/dashboard/filter-options/', views.signatory_filter_options_api, name='signatory_filter_options_api'),

    # Signatory Clearance API endpoints
    path('signatory/clearance/api/data/', views.signatory_clearance_data_api, name='signatory_clearance_data_api'),
    path('signatory/clearance/approve/', views.signatory_approve_clearance, name='signatory_approve_clearance'),
    path('signatory/clearance/disapprove/', views.signatory_disapprove_clearance, name='signatory_disapprove_clearance'),
    path('signatory/clearance/bulk-delete/', views.signatory_bulk_delete_clearance, name='signatory_bulk_delete_clearance'),
    path('signatory/clearance/bulk-approve/', views.signatory_bulk_approve_clearance, name='signatory_bulk_approve_clearance'),
    path('signatory/clearance/bulk-disapprove/', views.signatory_bulk_disapprove_clearance, name='signatory_bulk_disapprove_clearance'),
    path('signatory/clearance/print/<uuid:clearance_id>/', views.signatory_print_clearance, name='signatory_print_clearance'),
    path('signatory/clearance/bulk-print/', views.signatory_bulk_print_clearance, name='signatory_bulk_print_clearance'),
    path('signatory/clearance/preview-print/', views.signatory_bulk_print_clearance, name='signatory_preview_print_clearance'),
    path('signatory/set-pin/', views.signatory_set_pin, name='signatory_set_pin'),
    path('signatory/change-pin/', views.signatory_change_pin, name='signatory_change_pin'),
    path('signatory/change-password/', views.signatory_change_password, name='signatory_change_password'),
    path('signatory/clearance/filter-options/', views.signatory_clearance_filter_options, name='signatory_clearance_filter_options'),
    
    # Signatory Enrollment API endpoints
    path('signatory/enrollment/api/data/', views.signatory_enrollment_data_api, name='signatory_enrollment_data_api'),
    path('signatory/enrollment/filter-options/', views.signatory_enrollment_filter_options, name='signatory_enrollment_filter_options'),
    path('signatory/enrollment/approve/', views.signatory_approve_enrollment, name='signatory_approve_enrollment'),
    path('signatory/enrollment/disapprove/', views.signatory_disapprove_enrollment, name='signatory_disapprove_enrollment'),
    path('signatory/enrollment/print/<uuid:enrollment_id>/', views.signatory_print_enrollment, name='signatory_print_enrollment'),
    path('signatory/enrollment/bulk-approve/', views.signatory_bulk_approve_enrollment, name='signatory_bulk_approve_enrollment'),
    path('signatory/enrollment/bulk-disapprove/', views.signatory_bulk_disapprove_enrollment, name='signatory_bulk_disapprove_enrollment'),
    path('signatory/enrollment/bulk-print/', views.signatory_bulk_print_enrollment, name='signatory_bulk_print_enrollment'),
    path('signatory/enrollment/delete/<uuid:enrollment_id>/', views.signatory_delete_enrollment, name='signatory_delete_enrollment'),
    path('signatory/enrollment/bulk-delete/', views.signatory_bulk_delete_enrollment, name='signatory_bulk_delete_enrollment'),
    
    # Signatory Graduation API endpoints
    path('signatory/graduation/', views.signatory_graduation, name='signatory_graduation'),
    path('signatory/graduation/api/data/', views.signatory_graduation_data_api, name='signatory_graduation_data_api'),
    path('signatory/graduation/filter-options/', views.signatory_graduation_filter_options, name='signatory_graduation_filter_options'),
    path('signatory/graduation/approve/', views.signatory_approve_graduation, name='signatory_approve_graduation'),
    path('signatory/graduation/disapprove/', views.signatory_disapprove_graduation, name='signatory_disapprove_graduation'),
    path('signatory/graduation/bulk-approve/', views.signatory_bulk_approve_graduation, name='signatory_bulk_approve_graduation'),
    path('signatory/graduation/bulk-disapprove/', views.signatory_bulk_disapprove_graduation, name='signatory_bulk_disapprove_graduation'),
    path('signatory/graduation/view/<uuid:graduation_id>/', views.signatory_graduation_view, name='signatory_graduation_view'),
    path('signatory/graduation/print/<uuid:graduation_id>/', views.signatory_graduation_print, name='signatory_graduation_print'),
    path('signatory/graduation/bulk-print/', views.signatory_graduation_bulk_print, name='signatory_graduation_bulk_print'),
    
    # Signatory Reports API endpoints
    path('signatory/reports/api/data/', views.signatory_reports_data_api, name='signatory_reports_data_api'),
    path('signatory/reports/generated-list/', views.signatory_generated_reports_list, name='signatory_generated_reports_list'),
    path('signatory/reports/generate-auto-report/', views.signatory_generate_auto_report, name='signatory_generate_auto_report'),
    path('signatory/reports/download-report/<uuid:report_id>/', views.signatory_download_report, name='signatory_download_report'),
    path('signatory/clearance/verify-pin/', views.signatory_verify_pin, name='signatory_verify_pin'),
    path('signatory/check-setup-status/', views.signatory_check_setup_status, name='signatory_check_setup_status'),
    path('signatory/clearance/details/<uuid:clearance_id>/', views.signatory_get_clearance_details, name='signatory_get_clearance_details'),
    path('signatory/reports/generate-manual-report/', views.signatory_generate_manual_report, name='signatory_generate_manual_report'),
    path('signatory/reports/export/csv/', views.signatory_reports_csv_export, name='signatory_reports_csv_export'),

    path('signatory/profile/', views.signatory_profile, name='signatory_profile'),
    path('signatory/profile/api/data/', views.signatory_profile_data_api, name='signatory_profile_data_api'),
    path('signatory/profile/update/', views.signatory_profile_update_api, name='signatory_profile_update_api'),
    path('signatory/profile/change-password/', views.signatory_profile_change_password_api, name='signatory_profile_change_password_api'),
    path('signatory/profile/upload-picture/', views.signatory_profile_upload_picture_api, name='signatory_profile_upload_picture_api'),
    
    # ========================================
    # BUSINESS MANAGER URLS
    # ========================================
    path('business-manager/dashboard/', views.business_manager_dashboard, name='business_manager_dashboard'),
    path('business-manager/clearance/', views.business_manager_clearance, name='business_manager_clearance'),
    path('business-manager/dashboard/api/data/', views.business_manager_dashboard_data_api, name='business_manager_dashboard_data_api'),
    path('business-manager/dashboard/mark-seen/', views.business_manager_mark_clearance_seen, name='business_manager_mark_clearance_seen'),
    path('business-manager/clearance/api/data/', views.business_manager_clearance_data_api, name='business_manager_clearance_data_api'),
    path('business-manager/clearance/api/filter-options/', views.business_manager_clearance_filter_options, name='business_manager_clearance_filter_options'),
    path('business-manager/clearance/details/<uuid:clearance_id>/', views.business_manager_get_clearance_details, name='business_manager_get_clearance_details'),
    path('business-manager/calendar/api/events/', views.business_manager_calendar_events_api, name='business_manager_calendar_events_api'),
    path('business-manager/calendar/api/add-event/', views.business_manager_add_calendar_event, name='business_manager_add_calendar_event'),
    path('business-manager/clearance/approve/', views.business_manager_approve_clearance, name='business_manager_approve_clearance'),
    path('business-manager/clearance/disapprove/', views.business_manager_disapprove_clearance, name='business_manager_disapprove_clearance'),
    path('business-manager/clearance/delete/<uuid:clearance_id>/', views.business_manager_delete_clearance, name='business_manager_delete_clearance'),
    path('business-manager/clearance/bulk-approve/', views.business_manager_bulk_approve_clearance, name='business_manager_bulk_approve_clearance'),
    path('business-manager/clearance/bulk-disapprove/', views.business_manager_bulk_disapprove_clearance, name='business_manager_bulk_disapprove_clearance'),
    path('business-manager/clearance/bulk-delete/', views.business_manager_bulk_delete_clearance, name='business_manager_bulk_delete_clearance'),
    path('business-manager/clearance/preview-print/', views.business_manager_preview_print_clearance, name='business_manager_preview_print_clearance'),
    path('business-manager/verify-pin/', views.business_manager_verify_pin, name='business_manager_verify_pin'),
    path('business-manager/check-setup-status/', views.business_manager_check_setup_status, name='business_manager_check_setup_status'),
    path('business-manager/set-pin/', views.business_manager_set_pin, name='business_manager_set_pin'),
    path('business-manager/change-pin/', views.business_manager_change_pin, name='business_manager_change_pin'),
    path('business-manager/change-password/', views.business_manager_change_password, name='business_manager_change_password'),
    path('business-manager/enrollment/', views.business_manager_enrollment, name='business_manager_enrollment'),
    path('business-manager/enrollment/api/data/', views.business_manager_enrollment_data_api, name='business_manager_enrollment_data_api'),
    path('business-manager/enrollment/approve/', views.business_manager_approve_enrollment, name='business_manager_approve_enrollment'),
    path('business-manager/enrollment/disapprove/', views.business_manager_disapprove_enrollment, name='business_manager_disapprove_enrollment'),
    path('business-manager/enrollment/delete/<uuid:enrollment_id>/', views.business_manager_delete_enrollment, name='business_manager_delete_enrollment'),
    path('business-manager/enrollment/bulk-approve/', views.business_manager_bulk_approve_enrollment, name='business_manager_bulk_approve_enrollment'),
    path('business-manager/enrollment/bulk-disapprove/', views.business_manager_bulk_disapprove_enrollment, name='business_manager_bulk_disapprove_enrollment'),
    path('business-manager/enrollment/bulk-delete/', views.business_manager_bulk_delete_enrollment, name='business_manager_bulk_delete_enrollment'),
    path('business-manager/enrollment/preview-print/', views.business_manager_preview_print_enrollment, name='business_manager_preview_print_enrollment'),
    path('business-manager/graduation/', views.business_manager_graduation, name='business_manager_graduation'),
    path('business-manager/graduation/api/data/', views.business_manager_graduation_data_api, name='business_manager_graduation_data_api'),
    path('business-manager/graduation/approve/', views.business_manager_graduation_approve, name='business_manager_graduation_approve'),
    path('business-manager/graduation/disapprove/', views.business_manager_graduation_disapprove, name='business_manager_graduation_disapprove'),
    path('business-manager/graduation/delete/<uuid:graduation_id>/', views.business_manager_graduation_delete, name='business_manager_graduation_delete'),
    path('business-manager/graduation/bulk-approve/', views.business_manager_bulk_approve_graduation, name='business_manager_bulk_approve_graduation'),
    path('business-manager/graduation/bulk-disapprove/', views.business_manager_bulk_disapprove_graduation, name='business_manager_bulk_disapprove_graduation'),
    path('business-manager/graduation/bulk-delete/', views.business_manager_graduation_bulk_delete, name='business_manager_graduation_bulk_delete'),
    path('business-manager/graduation/edit-status/', views.business_manager_graduation_edit_status, name='business_manager_graduation_edit_status'),
    path('business-manager/graduation/preview-print/', views.business_manager_graduation_preview_print, name='business_manager_graduation_preview_print'),
    path('business-manager/graduation/view/<uuid:graduation_id>/', views.business_manager_graduation_view, name='business_manager_graduation_view'),
    path('business-manager/credential-request/', views.business_manager_credential_request, name='business_manager_credential_request'),
    path('business-manager/credential-request/approve/', views.business_manager_approve_credential, name='business_manager_approve_credential'),
    path('business-manager/credential-request/disapprove/', views.business_manager_disapprove_credential, name='business_manager_disapprove_credential'),
    path('business-manager/credential-request/edit-status/', views.business_manager_edit_credential_status, name='business_manager_edit_credential_status'),
    path('business-manager/credential-request/preview-print/', views.business_manager_preview_print_credential, name='business_manager_preview_print_credential'),
    path('business-manager/credential-request/delete/<uuid:credential_id>/', views.business_manager_delete_credential, name='business_manager_delete_credential'),
    path('business-manager/credential-request/bulk-approve/', views.business_manager_bulk_approve_credential, name='business_manager_bulk_approve_credential'),
    path('business-manager/credential-request/bulk-disapprove/', views.business_manager_bulk_disapprove_credential, name='business_manager_bulk_disapprove_credential'),
    path('business-manager/credential-request/bulk-delete/', views.business_manager_bulk_delete_credential, name='business_manager_bulk_delete_credential'),
    path('business-manager/reports/', views.business_manager_reports, name='business_manager_reports'),
    path('business-manager/reports/api/data/', views.business_manager_reports_data_api, name='business_manager_reports_data_api'),
    path('business-manager/reports/generated-list/', views.business_manager_generated_reports_list, name='business_manager_generated_reports_list'),
    path('business-manager/reports/generate-auto-report/', views.business_manager_generate_auto_report, name='business_manager_generate_auto_report'),
    path('business-manager/reports/generate-manual-report/', views.business_manager_generate_manual_report, name='business_manager_generate_manual_report'),
    path('business-manager/reports/download-report/<uuid:report_id>/', views.business_manager_download_report, name='business_manager_download_report'),
    path('business-manager/reports/export/csv/', views.business_manager_reports_csv_export, name='business_manager_reports_csv_export'),
    path('business-manager/profile/', views.business_manager_profile, name='business_manager_profile'),
    path('business-manager/profile/api/data/', views.business_manager_profile_data_api, name='business_manager_profile_data_api'),
    path('business-manager/profile/update/', views.business_manager_profile_update_api, name='business_manager_profile_update_api'),
    path('business-manager/profile/change-password/', views.business_manager_profile_change_password_api, name='business_manager_profile_change_password_api'),
    path('business-manager/profile/upload-picture/', views.business_manager_profile_upload_picture_api, name='business_manager_profile_upload_picture_api'),
    path('business-manager/messages/', views.business_manager_messages, name='business_manager_messages'),
    
    # ========================================
    # MOBILE API URLS
    # ========================================
    path('api/mobile/', include('landing.api_urls')),
]



# Add this to serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

